theme: jekyll-theme-primer

plugins:
  - jekyll-feed

title: Flessner.io
author: Torben Flessner
url: flessner.io

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "foam"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Torben Flessner"
  -
    scope:
      path: "de"
      type: "pages"
    values:
      layout: "kb"
      lang: "de-DE"
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "kb"
      lang: "en-US"