theme: jekyll-theme-primer

title: Flessner

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "foam"
  -
    scope:
      path: "blog"
      type: "pages"
    values:
      layout: "article"
      author: "Torben Flessner"
  -
    scope:
      path: "de"
      type: "pages"
    values:
      lang: "de-DE"
  -
    scope:
      path: "en"
      type: "pages"
    values:
      lang: "en-US"