theme: jekyll-theme-primer

title: Flessner

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "foam"
  -
    scope:
      path: "blog"
      type: "pages"
    values:
      layout: "article"
      author: "Torben Flessner"